### ISSUE TITLE
New Lines are being parsed properly?

### ISSUE THREAD

**Issue by phun** [urthbound/hound.vim#4]
![screen shot 2015-02-17 at 12 26 49 pm](https://cloud.githubusercontent.com/assets/410858/6233369/4495a818-b6a0-11e4-9788-cb23d399fe5e.png)

My lines are a little funky, sometimes it's not separated where it should be. I'll try to investigate the issue

**Comment by jfo** [comment]
This was fixed with:

https://github.com/urthbound/hound.vim/commit/9f51968ce3730197c702ee667aac92bb37280d6c

But do lmk if you see it after pulling.

**Comment by jfo** [comment]
actually sorry you're right just a sec.

**Comment by jfo** [comment]
https://github.com/urthbound/hound.vim/pull/6
