### ISSUE TITLE
Feature Request: Enter to open file

### ISSUE THREAD

**Issue by phun** [urthbound/hound.vim#5]
It'd be really cool if you can open the file by pressing <Enter> while on a line in the file, similar to how you open files with :Ex

**Comment by jfo** [comment]
You can already do this with `gf` (to open the file) and `gF` to open the file to the specified line assuming your working directory is the root of the repo you're looking at. I'm planning to add options to have a static path prefix that you can set to be able to jump to multiple repos.

I'm also not big on mapping keys in a plugin if I can avoid it for fear of clobbering predefined user mappings, but you're free to map `<CR>` to `gF` or something for your own use!

Something like:

``` viml
autocmd FileType houndresults map <CR> gf
```

Would probably work.

**Comment by jfo** [comment]
OH  I misunderstood, I see what you're saying... I will consider adding that!

**Comment by phun** [comment]
If you don't care too much about it and want to work on something else, I can try to tackle this and send over a pull request!

Oooo, `gF` does what I need it to do 99% of the time for now!

**Comment by jfo** [comment]
Let me think about this one some more, I am trepidatious about both the remap and unexpected behavior within the buffer. If there is a file name included in the snippet result I want it to `gf` as expected.

I think maybe better is to preload the `/` command with the regex that targets the filenames right now:

`^.*\(\n-----\)\@=`

Closing for now!
